export const CREATE_GAME = "CREATE_GAME";
export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const ADD_ROUND_TO_GAME = "ADD_ROUND_TO_GAME";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
export const CLEAN_GAME = "CLEAN_GAME";